Repository croct-tech/cli, pull requests merged in 2025-04, with the labels that each got.

#24 Fix minor issues
  src/application/api/workspace.ts
  src/application/cli/command/template/create.ts
  src/application/cli/io/logFormatter.ts
  src/application/cli/io/output.ts
  src/application/template/action/locateFileAction.ts
  src/application/template/action/printAction.ts
  src/application/template/resourceMatcher.ts
  src/infrastructure/application/api/graphql/workspace.ts
  src/infrastructure/application/cli/io/consoleOutput.ts
  src/infrastructure/application/cli/io/formatting.ts
  src/infrastructure/application/cli/io/interactiveTaskMonitor.ts
  src/infrastructure/application/cli/io/nonInteractiveTaskMonitor.ts
  src/infrastructure/application/validation/actions/createResourceOptionsValidator.ts
  src/infrastructure/application/validation/actions/locateFileOptionsValidator.ts
  src/infrastructure/application/validation/actions/printOptionsValidator.ts
  src/infrastructure/application/validation/actions/promptOptionsValidator.ts
  src/infrastructure/application/validation/croctConfigurationValidator.ts
  src/infrastructure/application/validation/zodValidator.ts
Labels: bc-break, maintenance

#25 Rename options and add default default values to template
  src/application/cli/command/template/create.ts
  src/application/template/action/importAction.ts
  src/application/template/template.ts
  src/infrastructure/application/cli/program.ts
  src/infrastructure/application/validation/templateValidator.ts
Labels: enhancement

#27 Allow dash in option names
  src/infrastructure/application/validation/templateValidator.ts
Labels: enhancement

#26 Add support for overriding files
  src/application/template/action/downloadAction.ts
  src/infrastructure/application/validation/actions/downloadOptionsValidator.ts
Labels: feature

#30 Fix eveluation
  src/infrastructure/application/evaluation/jsepExpressionEvaluator.ts
Labels: bug

#31 Redesign project path resolution
  src/application/project/configuration/projectConfiguration.ts
  src/application/project/sdk/javasScriptSdk.ts
  src/application/project/sdk/lazySdk.ts
  src/application/project/sdk/plugJsSdk.ts
  src/application/project/sdk/plugNextSdk.ts
  src/application/project/sdk/plugReactSdk.ts
  src/application/project/sdk/sdk.ts
  src/infrastructure/application/cli/cli.ts
  src/infrastructure/application/validation/croctConfigurationValidator.ts
  src/infrastructure/application/validation/zodValidator.ts
Labels: enhancement

#28 Add support for overwriting files
  src/application/template/action/downloadAction.ts
Labels: feature

#29 Set omitted options to null
  src/application/template/action/importAction.ts
Labels: enhancement

#32 Fix path resolution logic
  src/application/project/sdk/javasScriptSdk.ts
Labels: bug

#34 Add auto-update for deep links
  src/application/cli/command/open.ts
  src/application/cli/command/welcome.ts
  src/application/cli/configuration/fileConfigurationStore.ts
  src/application/cli/configuration/normalizedConfigurationStore.ts
  src/application/cli/configuration/provider.ts
  src/application/project/configuration/manager/indexedConfigurationManager.ts
  src/application/project/packageManager/agent/executableAgent.ts
  src/application/project/server/processServer.ts
  src/application/system/executableLocator.ts
  src/application/system/process/executor.ts
  src/application/system/protocol/linuxRegistry.ts
  src/application/system/protocol/macOsRegistry.ts
  src/application/system/protocol/windowsRegistry.ts
  src/application/template/action/executePackage.ts
  src/infrastructure/application/cli/cli.ts
  src/infrastructure/application/cli/program.ts
  src/infrastructure/application/project/javaScriptFormatter.ts
  src/infrastructure/application/system/command/spawnExecutor.ts
  src/infrastructure/application/validation/cliSettingsValidator.ts
Labels: enhancement

#36 Restore version tracking
  src/application/cli/command/welcome.ts
Labels: bug

#37 Remove slot selection from initialization
  src/application/cli/command/init.ts
Labels: enhancement

#38 Add support for renaming downloaded files
  src/application/template/action/downloadAction.ts
  src/infrastructure/application/validation/actions/downloadOptionsValidator.ts
Labels: feature

#39 Fix path resolution
  src/application/cli/command/init.ts
  src/application/project/code/transformation/globImportCodemod.ts
  src/application/project/import/nodeImportResolver.ts
  src/application/project/sdk/javasScriptSdk.ts
Labels: bug

#40 Fix overwrite option
  src/infrastructure/application/validation/actions/downloadOptionsValidator.ts
Labels: bug

#42 Fix component refactoring
  src/application/template/resourceRefactor.ts
Labels: bug

#43 Use cross-spawn and remove ansi screen emulator
  src/application/system/protocol/macOsRegistry.ts
  src/application/template/action/executePackage.ts
  src/infrastructure/application/system/command/spawnExecutor.ts
Labels: bug

#44 Extract logic resolve command
  src/infrastructure/application/cli/cli.ts
  src/infrastructure/application/system/command/resolvedCommandExecutor.ts
  src/infrastructure/application/system/command/spawnExecutor.ts
Labels: enhancement

#45 Expose more array methods
  src/infrastructure/application/evaluation/jsepExpressionEvaluator.ts
Labels: feature

#46 Correct validation at workspace resource creation
  src/infrastructure/application/validation/actions/createResourceOptionsValidator.ts
Labels: bug

#47 Allow metadata in templates
  src/infrastructure/application/validation/templateValidator.ts
Labels: bug

#48 Fix action name
  src/infrastructure/application/cli/cli.ts
Labels: bug

#49 Fix deep links
  src/application/system/protocol/macOsRegistry.ts
  src/infrastructure/application/cli/program.ts
Labels: bug

#50 Fix create resource validation
  src/application/api/workspace.ts
  src/application/template/resourceMatcher.ts
  src/application/template/resourceRefactor.ts
  src/application/template/resources.ts
  src/infrastructure/application/api/graphql/workspace.ts
  src/infrastructure/application/validation/actions/createResourceOptionsValidator.ts
Labels: bug

#51 Add support for scoped NPM URLs
  src/application/cli/command/template/use.ts
  src/application/provider/resource/npmRegistryProvider.ts
  src/application/template/action/importAction.ts
Labels: bug

#52 Improve error handling
  src/application/cli/form/organization/organizationForm.ts
  src/application/template/action/changeDirectoryAction.ts
  src/application/template/action/executePackage.ts
  src/application/template/action/importAction.ts
  src/infrastructure/application/cli/cli.ts
  src/infrastructure/application/cli/io/interactiveTaskMonitor.ts
  src/infrastructure/application/system/command/spawnExecutor.ts
Labels: bug, enhancement

#53 Remove inactivity timeout and optimize rendering
  src/infrastructure/application/cli/io/interactiveTaskMonitor.ts
Labels: bug, enhancement

#54 Remove command timeout
  src/application/template/action/executePackage.ts
  src/infrastructure/application/cli/cli.ts
Labels: bug

#55 Fix action logic
  src/application/template/action/checkDependencyAction.ts
  src/infrastructure/application/cli/cli.ts
Labels: bug
